import type { CatalogItem } from '../types'

export const builtinCatalog: CatalogItem[] = [
  {
    id: 'fr-a1-greetings',
    title: 'Приветствия',
    language: 'fr',
    level: 'A1',
    kind: 'cards',
    path: '/library/cards/fr-a1-greetings.json',
    description: 'Базовые формулы вежливости и знакомства',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'fr-a1-food',
    title: 'Еда и кафе',
    language: 'fr',
    level: 'A1',
    kind: 'cards',
    path: '/library/cards/fr-a1-food.json',
    description: 'Слова для заказа и меню',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'de-a1-greetings',
    title: 'Приветствия',
    language: 'de',
    level: 'A1',
    kind: 'cards',
    path: '/library/cards/de-a1-greetings.json',
    description: 'Hallo, Danke и первые диалоги',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'de-a1-articles',
    title: 'der / die / das',
    language: 'de',
    level: 'A1',
    kind: 'cards',
    path: '/library/cards/de-a1-articles.json',
    description: 'Существительные с родом',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'en-a1-greetings',
    title: 'Приветствия',
    language: 'en',
    level: 'A1',
    kind: 'cards',
    path: '/library/cards/en-a1-greetings.json',
    description: 'Повседневные приветствия и вежливость',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'en-a1-verbs',
    title: 'Неправильные глаголы',
    language: 'en',
    level: 'A2',
    kind: 'cards',
    path: '/library/cards/en-a1-verbs.json',
    description: 'go / went / gone и другие формы',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'fr-spell-core',
    title: 'Орфография A1',
    language: 'fr',
    level: 'A1',
    kind: 'puzzles',
    path: '/library/puzzles/fr-spell-core.json',
    description: 'Соберите короткие французские слова',
    words: 10,
    source: 'builtin',
  },
  {
    id: 'de-spell-core',
    title: 'Буквы и умлауты',
    language: 'de',
    level: 'A1',
    kind: 'puzzles',
    path: '/library/puzzles/de-spell-core.json',
    description: 'Соберите немецкие слова по буквам',
    words: 10,
    source: 'builtin',
  },
  {
    id: 'en-spell-core',
    title: 'Орфография A1',
    language: 'en',
    level: 'A1',
    kind: 'puzzles',
    path: '/library/puzzles/en-spell-core.json',
    description: 'Соберите английские слова',
    words: 10,
    source: 'builtin',
  },
  {
    id: 'fr-cafe-talk',
    title: 'В кафе',
    language: 'fr',
    level: 'A1',
    kind: 'sentences',
    path: '/library/sentences/fr-cafe-talk.json',
    description: 'Фразы для заказа и счёта',
    words: 8,
    source: 'builtin',
  },
  {
    id: 'de-city-talk',
    title: 'В городе',
    language: 'de',
    level: 'A1',
    kind: 'sentences',
    path: '/library/sentences/de-city-talk.json',
    description: 'Как спросить дорогу и купить билет',
    words: 8,
    source: 'builtin',
  },
  {
    id: 'en-travel-talk',
    title: 'В поездке',
    language: 'en',
    level: 'A1',
    kind: 'sentences',
    path: '/library/sentences/en-travel-talk.json',
    description: 'Короткие фразы в поездке',
    words: 8,
    source: 'builtin',
  },
  {
    id: 'fr-core-pairs',
    title: 'Базовый словарь',
    language: 'fr',
    level: 'A1',
    kind: 'translations',
    path: '/library/translations/fr-core-pairs.json',
    description: 'FR ↔ RU на скорость',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'de-core-pairs',
    title: 'Базовый словарь',
    language: 'de',
    level: 'A1',
    kind: 'translations',
    path: '/library/translations/de-core-pairs.json',
    description: 'DE ↔ RU на скорость',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'en-core-pairs',
    title: 'Базовый словарь',
    language: 'en',
    level: 'A1',
    kind: 'translations',
    path: '/library/translations/en-core-pairs.json',
    description: 'EN ↔ RU на скорость',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'fr-match-core',
    title: 'Пары A1',
    language: 'fr',
    level: 'A1',
    kind: 'matching',
    path: '/library/matching/fr-match-core.json',
    description: 'Свяжите французское слово с русским',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'de-match-core',
    title: 'Пары A1',
    language: 'de',
    level: 'A1',
    kind: 'matching',
    path: '/library/matching/de-match-core.json',
    description: 'Свяжите немецкое слово с русским',
    words: 12,
    source: 'builtin',
  },
  {
    id: 'en-match-core',
    title: 'Пары A1',
    language: 'en',
    level: 'A1',
    kind: 'matching',
    path: '/library/matching/en-match-core.json',
    description: 'Свяжите английское слово с русским',
    words: 12,
    source: 'builtin',
  },
]
